version: "3.8"

services:
  api:
    image: danielbrilho223/servico_destribuido:v1.0
    ports:
      - "8000:8000"
    restart: always
    environment:
      - DATABASE_URL=postgresql://daniels:alice223@db:5432/meus_dados
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: daniels
      POSTGRES_PASSWORD: alice223
      POSTGRES_DB: meus_dados
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:

